document.write('    <div id="arithmetic_operator" class="topic">');
document.write('      <div class="topic-name mb-4">');
document.write('        <h2>Arithmetic Operator</h2>');
document.write('      </div>');
document.write('      <div class="topic-body">');
document.write('        <table class="table table-bordered table-danger table-hover table-striped">');
document.write('          <tr>');
document.write('            <th>Name</th>');
document.write('            <th>Operator</th>');
document.write('            <th>Usage</th>');
document.write('            <th>Description</th>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td>Plus</td>');
document.write('            <td class="random3">+</td>');
document.write('            <td class="random3">a + b</td>');
document.write('            <td>Performing Addition on variable a and b</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td>Minus</td>');
document.write('            <td class="random3">-</td>');
document.write('            <td class="random3">c - 10</td>');
document.write('            <td>Subtracting 10 from variable c</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td>Divide</td>');
document.write('            <td class="random3">/</td>');
document.write('            <td class="random3">10 / 2</td>');
document.write('            <td>Dividing 10 by 2</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td>Multiply</td>');
document.write('            <td class="random3">*</td>');
document.write('            <td class="random3">2 * 2</td>');
document.write('            <td>Multiplying 2 with 2</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td>Modulus / Remainder</td>');
document.write('            <td class="random3">%</td>');
document.write('            <td class="random3">3 % 2</td>');
document.write('            <td>Dividing 3 by 2, to get Remainder</td>');
document.write('          </tr>');
document.write('        </table>');
document.write('        <h2 class="mt-4">INBUILT ARITHMETIC FUNCTIONS</h2>');
document.write('<table class="table table-dark table-bordered table-striped table-hover">');
document.write('  <tr>');
document.write('    <th>Function</th>');
document.write('    <td><span class="bold">Description</span> <span class="text-warning ubuntu-font">(LIBS: <span class="random6">math.h</span>, <span class="random6">stdlib.h</span>)</span></td>');
document.write('  <tr>');
document.write('  <tr>');
document.write('    <td class="random3 text-danger">abs()</td>');
document.write('    <td>returns positive absolute value of int.</td>');
document.write('  <tr>');
document.write('    <td class="random3 text-danger">floor()</td>');
document.write('    <td>returns nearest integer which is less than or equal to the given argument.</td>');
document.write('  <tr>');
document.write('    <td class="random3 text-danger">round()</td>');
document.write('    <td>Takes float,double,long double and returns rounded int</td>');
document.write('  <tr>');
document.write('    <td class="random3 text-danger">ceil()</td>');
document.write('    <td>returns nearest integer value which is greater than or equal to the given argument.</td>');
document.write('  <tr>');
document.write('    <td class="random3 text-danger">sin()</td>');
document.write('    <td>Used to calculate sine value.</td>');
document.write('  <tr>');
document.write('    <td class="random3 text-danger">cos()</td>');
document.write('    <td>Used to calculate cosine.</td>');
document.write('  <tr>');
document.write('    <td class="random3 text-danger">cosh()</td>');
document.write('    <td>Used to calculate hyperbolic cosine.</td>');
document.write('  <tr>');
document.write('    <td class="random3 text-danger">exp()</td>');
document.write('    <td>Used to calculate the exponential &quot;e&quot; to the x<sup>th</sup> power.</td>');
document.write('  <tr>');
document.write('    <td class="random3 text-danger">tan()</td>');
document.write('    <td>Used to calculate tangent.</td>');
document.write('  <tr>');
document.write('    <td class="random3 text-danger">tanh()</td>');
document.write('    <td>Used to calculate hyperbolic tangent.</td>');
document.write('  <tr>');
document.write('    <td class="random3 text-danger">sinh()</td>');
document.write('    <td>Used to calculate hyperbolic sine.</td>');
document.write('  <tr>');
document.write('    <td class="random3 text-danger">log()</td>');
document.write('    <td>Used to calculates natural logarithm.</td>');
document.write('  <tr>');
document.write('    <td class="random3 text-danger">log10()</td>');
document.write('    <td>Used to calculates base 10 logarithm.</td>');
document.write('  <tr>');
document.write('    <td class="random3 text-danger">sqrt()</td>');
document.write('    <td>Used to find square root of the Given argument.</td>');
document.write('  <tr>');
document.write('    <td class="random3 text-danger">pow()</td>');
document.write('    <td>Used to find power of the given number.</td>');
document.write('  <tr>');
document.write('    <td class="random3 text-danger">trunc()</td>');
document.write('    <td>Used to truncate decimal value from float value and return int.</td>');
document.write('</table>');
document.write('      </div>');
document.write('    </div>');
