document.write('    <div id="arrays" class="topic">');
document.write('      <div class="topic-name mb-4">');
document.write('        <h2>Arrays</h2>');
document.write('      </div>');
document.write('      <div class="topic-body">');
document.write('        <ul>');
document.write('          <li>Arrays Can Store Several Data</li>');
document.write('          <li>Syntax : <span class="random3">dataType arrayName[arraySize] = 	&#123;element1, element2,...&#125;</span>;</li>');
document.write('          <li>Array Name is Variable</li>');
document.write('          <li>Array index Starts at 0</li>');
document.write('        </ul>');
document.write('        <div class="code_box_long text-center mt-5">');
document.write('          <p>int <span class="random6">jungle</span>[<span class="text-warning">5</span>] = &#123;3,8,10,32,11&#125;;</p>');
document.write('        </div>');
document.write('');
document.write('        <table class="table table-bordered table-hover table-striped table-dark mt-4">');
document.write('          <tr>');
document.write('            <th>Statement</th>');
document.write('            <th>Question</th>');
document.write('            <th>Result</th>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3">printf(<span class="random9">&quot;%d&quot;</span>,<span class="random6">jungle</span>[<span class="text-warning">0</span>]);</td>');
document.write('            <td>Output?</td>');
document.write('            <td>3</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3">printf(<span class="random9">&quot;%d&quot;</span>,<span class="random6">jungle</span>[<span class="text-warning">2</span>]);</td>');
document.write('            <td>Output?</td>');
document.write('            <td>10</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3">printf(<span class="random9">&quot;%d&quot;</span>,<span class="random6">jungle</span>[<span class="text-warning">4</span>]);</td>');
document.write('            <td>Output?</td>');
document.write('            <td>11</td>');
document.write('          </tr>');
document.write('        </table>');
document.write('      </div>');
document.write('    </div>');
