document.write('    <div id="assignment_operator" class="topic">');
document.write('      <div class="topic-name mb-4">');
document.write('        <h2>Assignment Operator</h2>');
document.write('      </div>');
document.write('      <div class="topic-body">');
document.write('        <p>It assigns RHS_value to its LHS_variable, after manipulating !</p>');
document.write('        <p class="code_block mb-4">char <span class="text-warning">cute[3]</span> = <span class="text-success">&quot;no&quot;</span>;</p>');
document.write('        <table class="table table-bordered table-hover table-striped table-info">');
document.write('          <tr>');
document.write('            <th>Operator</th>');
document.write('            <th>Usage</th>');
document.write('            <th>Description</th>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3">=</td>');
document.write('            <td class="random3">int a = 10;</td>');
document.write('            <td>Assigning value 10 to variable a</td>');
document.write('          </tr>');
document.write('        </table>');
document.write('      </div>');
document.write('    </div>');
