document.write('    <div id="break" class="topic">');
document.write('      <div class="topic-name mb-4">');
document.write('        <h2>break</h2>');
document.write('      </div>');
document.write('      <div class="topic-body">');
document.write('        <p>It Stops Execution of Currently Executing Block !</p>');
document.write('        <p class="code_block"><span class="text-primary">break</span>;</p>');
document.write('        <div class="row">');
document.write('          <div class="col-md-6 col-lg-6">');
document.write('            <h2 class="text-center mb-4 mt-3">Code</h2>');
document.write('            <div class="code_box_long">');
document.write('              <p>int <span class="random9">a</span> = <span class="text-warning">1</span>;</p>');
document.write('              <p>while (<span class="random7">a &lt; 5</span>) &#123;</p>');
document.write('              <p>&nbsp;&nbsp;&nbsp;&nbsp;printf(<span class="random5">&quot;SINGH&quot;</span>);</p>');
document.write('              <p>&nbsp;&nbsp;&nbsp;&nbsp;<span class="text-primary">break</span>;</p>');
document.write('              <p>&#125;</p>');
document.write('              <p>printf(<span class="random5">&quot;&nbsp;IS KING !&quot;</span>);</p>');
document.write('            </div>');
document.write('          </div>');
document.write('          <div class="col-md-6 col-lg-6">');
document.write('            <h2 class="text-center mb-4 mt-3">Output</h2>');
document.write('            <div class="code_box_long">');
document.write('              <p>SINGH IS KING !</p>');
document.write('            </div>');
document.write('          </div>');
document.write('        </div>');
document.write('      </div>');
document.write('    </div>');
