document.write('<div id="characters" class="topic">');
document.write('  <div class="topic-name mb-4">');
document.write('    <h2>Characters</h2>');
document.write('  </div>');
document.write('  <div class="topic-body">');
document.write('    <p>Any single element enclosed in Single Quotes is character, </p>');
document.write('    <p class="code_block"><span class="random6">char</span> <span class="text-warning">a</span> = <span class="random5">&apos;7&apos;</span>;</p>');
document.write('    <h2 class="mt-4 mb-4">INBUILT FUNCTIONS FOR CHARACTERS</h2>');
document.write('    <table class="table table-bordered table-dark table-striped table-hover">');
document.write('      <tr>');
document.write('        <th>Functions</th>');
document.write('        <td><span class="bold">Description</span> <span class="text-warning ubuntu-font">(LIB: <span class="random6">ctype.h</span>)</span></td>');
document.write('      </tr>');
document.write('      <tr>');
document.write('        <td class="random3 text-danger">isalpha()</td>');
document.write('        <td>checks character is alphabet</td>');
document.write('      </tr>');
document.write('      <tr>');
document.write('        <td class="random3 text-danger">isdigit()</td>');
document.write('        <td>checks character is digit</td>');
document.write('      </tr>');
document.write('      <tr>');
document.write('        <td class="random3 text-danger">isalnum()</td>');
document.write('        <td>Checks character is alphanumeric</td>');
document.write('      </tr>');
document.write('      <tr>');
document.write('        <td class="random3 text-danger">isspace()</td>');
document.write('        <td>Checks character is space</td>');
document.write('      </tr>');
document.write('      <tr>');
document.write('        <td class="random3 text-danger">islower()</td>');
document.write('        <td>Checks character is lower case</td>');
document.write('      </tr>');
document.write('      <tr>');
document.write('        <td class="random3 text-danger">isupper()</td>');
document.write('        <td>Checks character is UPPER CASE</td>');
document.write('      </tr>');
document.write('      <tr>');
document.write('        <td class="random3 text-danger">isxdigit()</td>');
document.write('        <td>Checks character is hexadecimal</td>');
document.write('      </tr>');
document.write('      <tr>');
document.write('        <td class="random3 text-danger">iscntrl()</td>');
document.write('        <td>Checks character is a control character</td>');
document.write('      </tr>');
document.write('      <tr>');
document.write('        <td class="random3 text-danger">isprint()</td>');
document.write('        <td>Checks character is a printable character</td>');
document.write('      </tr>');
document.write('      <tr>');
document.write('        <td class="random3 text-danger">ispunct()</td>');
document.write('        <td>Checks character is a punctuation</td>');
document.write('      </tr>');
document.write('      <tr>');
document.write('        <td class="random3 text-danger">isgraph()</td>');
document.write('        <td>Checks character is a graphical character</td>');
document.write('      </tr>');
document.write('      <tr>');
document.write('        <td class="random3 text-danger">tolower()</td>');
document.write('        <td>Converts character to lower case</td>');
document.write('      </tr>');
document.write('      <tr>');
document.write('        <td class="random3 text-danger">toupper()</td>');
document.write('        <td>Converts character to UPPER CASE</td>');
document.write('      </tr>');
document.write('    </table>');
document.write('  </div>');
document.write('</div>');
