document.write('    <div id="comments" class="topic">');
document.write('      <div class="topic-name mb-4">');
document.write('        <h2>Comments</h2>');
document.write('      </div>');
document.write('      <div class="topic-body">');
document.write('        <p>Single Line Comments Starts with double Slash <span class="random3">//</span></p>');
document.write('        <p>Multi Line Comments Starts with <span class="random3">/*</span> and end at <span class="random3">*/</span></p>');
document.write('        <br>');
document.write('        <div class="code_box text-center">');
document.write('          <p><span class="text-warning">//</span> <span class="text-secondary">I Love Coding !</span></p>');
document.write('        </div>');
document.write('        <br>');
document.write('        <div class="code_box_long text-center">');
document.write('          <p><span class="random7">/*</span> <span class="text-secondary">Yeah, breakfast at Tiffany&apos;s and bottles of bubbles</span></p>');
document.write('          <p><span class="text-secondary">Girls with tattoos who like getting in trouble</span></p>');
document.write('          <p><span class="text-secondary">Lashes and diamonds, ATM machines</span></p>');
document.write('          <p><span class="text-secondary">Buy myself all of my favorite things (yeah)</span> <span class="random7">*/</span></p>');
document.write('        </div>');
document.write('      </div>');
document.write('    </div>');
