document.write('    <div id="compound_assignment_operator" class="topic">');
document.write('      <div class="topic-name mb-4">');
document.write('        <h2>Compound Assignment Operator</h2>');
document.write('      </div>');
document.write('      <div class="topic-body">');
document.write('        <table class="table table-bordered table-hover table-striped table-info">');
document.write('          <tr>');
document.write('            <th>Operator</th>');
document.write('            <th>Usage</th>');
document.write('            <th>Alternative Way</th>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3">+=</td>');
document.write('            <td class="random3">a += 2</td>');
document.write('            <td class="random3">a = a + 2</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3">-=</td>');
document.write('            <td class="random3">a -= 2</td>');
document.write('            <td class="random3">a = a - 2</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3">/=</td>');
document.write('            <td class="random3">a /= 2</td>');
document.write('            <td class="random3">a = a / 2</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3">*=</td>');
document.write('            <td class="random3">a *= 5</td>');
document.write('            <td class="random3">a = a * 5</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3">%=</td>');
document.write('            <td class="random3">a %= 3</td>');
document.write('            <td class="random3">a = a % 3</td>');
document.write('          </tr>');
document.write('        </table>');
document.write('      </div>');
document.write('    </div>');
