document.write('    <div id="conditional_operator" class="topic">');
document.write('      <div class="topic-name mb-4">');
document.write('        <h2>Conditional / Ternary Operator</h2>');
document.write('      </div>');
document.write('      <div class="topic-body">');
document.write('        <ul>');
document.write('          <li>It returns value according to condition evaluation</li>');
document.write('          <li>Syntax : <span class="random3">(Condition ? true_value : false_value);</span></li>');
document.write('        </ul>');
document.write('        <p class="code_block">int <span class="random6">x</span> = <span class="text-warning">5</span>;</p>');
document.write('        <table class="table table-bordered table-hover table-striped table-dark mt-4">');
document.write('          <tr>');
document.write('            <th>Statement</th>');
document.write('            <th>Question</th>');
document.write('            <th>Result</th>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3">int <span class="random6">y</span> = ( <span class="random7">x == 5</span> ? <span class="text-warning">7</span> : <span class="text-warning">9</span>);</td>');
document.write('            <td>y = ?</td>');
document.write('            <td>7</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3">int <span class="random6">z</span> = ( <span class="random7">x == 4</span> ? <span class="text-warning">7</span> : <span class="text-warning">9</span>);</td>');
document.write('            <td>z = ?</td>');
document.write('            <td>9</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3"><span class="random7">x <= 5</span> ? printf(<span class="random5">&quot;%d YAY !&quot;</span>,<span class="random6">z</span>) : printf(<span class="random5">&quot;NAY !&quot;</span>);</td>');
document.write('            <td>Output?</td>');
document.write('            <td>9 YAY !</td>');
document.write('          </tr>');
document.write('        </table>');
document.write('        <div class="code_box mt-5">');
document.write('          <p></p>');
document.write('          <p></p>');
document.write('        </div>');
document.write('        <p></p>');
document.write('      </div>');
document.write('    </div>');
