document.write('    <div id="continue_keyword" class="topic">');
document.write('      <div class="topic-name mb-4">');
document.write('        <h2>continue</h2>');
document.write('      </div>');
document.write('      <div class="topic-body">');
document.write('        <p>It Moves Execution of Currently Executing Block to Start !</p>');
document.write('        <p class="code_block"><span class="text-primary">continue</span>;</p>');
document.write('        <div class="row">');
document.write('          <div class="col-md-6 col-lg-6">');
document.write('            <h2 class="text-center mb-4 mt-3">Code</h2>');
document.write('            <div class="code_box_long">');
document.write('              <p>int <span class="random9">a</span> = <span class="text-warning">1</span>;</p>');
document.write('              <p>while (<span class="random7">a &lt; 5</span>) &#123;</p>');
document.write('              <p>&nbsp;&nbsp;&nbsp;&nbsp;printf(<span class="random5">&quot;<span class="random9">%d</span><span class="text-primary">\\n</span>&quot;</span>,<span class="random6">a</span>);</p>');
document.write('              <p>&nbsp;&nbsp;&nbsp;&nbsp;a++;</p>');
document.write('              <p>&nbsp;&nbsp;&nbsp;&nbsp;<span class="text-primary">continue</span>;</p>');
document.write('              <p>&nbsp;&nbsp;&nbsp;&nbsp;printf(<span class="random5">&quot;KING&quot;</span>);</p>');
document.write('              <p>&#125;</p>');
document.write('            </div>');
document.write('          </div>');
document.write('          <div class="col-md-6 col-lg-6">');
document.write('            <h2 class="text-center mb-4 mt-3">Output</h2>');
document.write('            <div class="code_box">');
document.write('              <p>1</p>');
document.write('              <p>2</p>');
document.write('              <p>3</p>');
document.write('              <p>4</p>');
document.write('            </div>');
document.write('          </div>');
document.write('        </div>');
document.write('      </div>');
document.write('    </div>');
