document.write('    <div id="data_types" class="topic">');
document.write('      <div class="topic-name mb-4">');
document.write('        <h2>Data Types</h2>');
document.write('      </div>');
document.write('      <div class="topic-body">');
document.write('        <p>Each variable is declared with a datatype to store value of that datatype in it.</p>');
document.write('        <p>There are Several Data Types: </p>');
document.write('        <table class="table table-dark table-bordered table-striped table-hover">');
document.write('          <tr>');
document.write('            <th>Data Type</th>');
document.write('            <th>Value</th>');
document.write('            <th>Description</th>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td>int</td>');
document.write('            <td>1, 10, 923</td>');
document.write('            <td>Stores Integers in range of -32,768 to 32,767 !</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td>float</td>');
document.write('            <td>0.1, 1.0, 9.23</td>');
document.write('            <td>Stores Decimal upto 6 Precision !</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td>char</td>');
document.write('            <td>&apos;a&apos;, &apos;b&apos;, &apos;H&apos;</td>');
document.write('            <td>Stores Single Character, enclosed in Single quotes !</td>');
document.write('          </tr>');
document.write('        </table>');
document.write('      </div>');
document.write('    </div>');
