document.write('    <div id="escape_sequences" class="topic">');
document.write('      <div class="topic-name mb-4">');
document.write('        <h2>Escape Sequences</h2>');
document.write('      </div>');
document.write('      <div class="topic-body">');
document.write('        <table class="table table-bordered table-striped table-danger">');
document.write('          <tr>');
document.write('            <th>Escape Sequence</th>');
document.write('            <th>Description</th>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3">&#92;a</td>');
document.write('            <td>Alarm or Beep</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3">&#92;b</td>');
document.write('            <td>Backspace</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3">&#92;f</td>');
document.write('            <td>Form Feed</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3">&#92;n</td>');
document.write('            <td>New Line</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3">&#92;r</td>');
document.write('            <td>Carriage Return</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3">&#92;t</td>');
document.write('            <td>Tab (Horizontal)</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3">&#92;v</td>');
document.write('            <td>Vertical Tab</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3">&#92;&#92;</td>');
document.write('            <td>Backslash</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3">&#92;&apos;</td>');
document.write('            <td>Single Quote</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3">&#92;&quot;</td>');
document.write('            <td>Double Quote</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3">&#92;?</td>');
document.write('            <td>Question Mark</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3">&#92;ooo</td>');
document.write('            <td>octal number</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3">&#92;xhh</td>');
document.write('            <td>hexadecimal number</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3">&#92;0</td>');
document.write('            <td>Null</td>');
document.write('          </tr>');
document.write('        </table>');
document.write('      </div>');
document.write('    </div>');
