document.write('    <div id="expressions" class="topic">');
document.write('      <div class="topic-name mb-4">');
document.write('        <h2>Expressions</h2>');
document.write('      </div>');
document.write('      <div class="topic-body">');
document.write('        <div class="code_box">');
document.write('          <p>int <span class="random6">a</span>,<span class="random6">b</span>,<span class="random6">c</span>,<span class="random6">d</span>;</p>');
document.write('          <p><span class="random6">a</span> = <span class="int_color">1</span>;</p>');
document.write('          <p><span class="random6">b</span> = <span class="int_color">3</span>;</p>');
document.write('          <p><span class="random6">c</span> = <span class="int_color">9</span>;</p>');
document.write('          <p><span class="random6">d</span> = <span class="int_color">8</span>;</p>');
document.write('        </div>');
document.write('        <table class="table table-bordered table-warning table-striped table-hover">');
document.write('          <tr>');
document.write('            <th>Expressions</th>');
document.write('            <th>Result</th>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3">a + b * c / d;</td>');
document.write('            <td>4</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3">a - b / 3 + c * 2 - 1;</td>');
document.write('            <td>17</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3">((d + a) - 9) * b;</td>');
document.write('            <td>0</td>');
document.write('          </tr>');
document.write('        </table>');
document.write('      </div>');
document.write('    </div>');
