document.write('    <div id="field_width_specifier" class="topic">');
document.write('      <div class="topic-name mb-4">');
document.write('        <h2>Field Width Specifier</h2>');
document.write('      </div>');
document.write('      <div class="topic-body">');
document.write('        <p>If value becomes smaller than expectation, a field width adds spaces before it to to fill width !</p>');
document.write('        <table class="table table-bordered table-striped table-dark">');
document.write('          <tr>');
document.write('            <th>Statement</th>');
document.write('            <th>Result</th>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3">printf(<span class="random9">&quot;%4d&quot;</span>, <span class="text-primary">55</span>);</td>');
document.write('            <td class="random3"><span class="bg-danger">&nbsp;</span><span class="bg-warning">&nbsp;</span>55</td>');
document.write('          </tr>');
document.write('          <tr class="bg-dark">');
document.write('            <td class="random3">printf(<span class="random9">&quot;%4d&quot;</span>, <span class="text-primary">4</span>);</td>');
document.write('            <td class="random3"><span class="bg-danger">&nbsp;</span><span class="bg-warning">&nbsp;</span><span class="bg-primary">&nbsp;</span>4</td>');
document.write('          </tr>');
document.write('        </table>');
document.write('      </div>');
document.write('    </div>');
