document.write('    <div id="for_loop" class="topic">');
document.write('      <div class="topic-name mb-4">');
document.write('        <h2>for Loop</h2>');
document.write('      </div>');
document.write('      <div class="topic-body">');
document.write('        <p>It&apos;s favorite one of Programmers !</p>');
document.write('        <div class="syntax_box">');
document.write('          <p class="mt-2">for (initialization; condition; increment/decrement) &#123;</p>');
document.write('            <p>&nbsp;&nbsp;&nbsp;&nbsp;// Statements</p>');
document.write('          <p>&#125;</p>');
document.write('        </div>');
document.write('        <p class="mt-5">Optional</p>');
document.write('        <ul>');
document.write('          <li class="random3">initialization</li>');
document.write('          <li class="random3">increment / decrement</li>');
document.write('        </ul>');
document.write('        <div class="syntax_box">');
document.write('          <p class="mt-2">for (; condition;) &#123;</p>');
document.write('            <p>&nbsp;&nbsp;&nbsp;&nbsp;// Statements</p>');
document.write('          <p>&#125;</p>');
document.write('        </div>');
document.write('        <div class="row mb-3">');
document.write('            <div class="col-md-6 col-lg-6">');
document.write('              <h3 class="text-center mb-4 mt-3">Code</h3>');
document.write('                <div class="code_box_longest">');
document.write('                  <p>int <span class="random6">a;</p>');
document.write('                  <p class="mt-2">for (a = 1; a <= 5; a++) &#123;</p>');
document.write('                  <p>&nbsp;&nbsp;&nbsp;&nbsp;printf(<span class="random5">&quot;<span class="random9">%d</span><span class="text-primary">\\n</span>&quot;</span>,<span class="random6">a</span>);</p>');
document.write('                  <p>&#125;</p>');
document.write('                </div>');
document.write('            </div>');
document.write('            <div class="col-md-6 col-lg-6">');
document.write('              <h3 class="text-center mb-4 mt-3">Output</h3>');
document.write('              <div class="code_box_long">');
document.write('                <p>1</p>');
document.write('                <p>2</p>');
document.write('                <p>3</p>');
document.write('                <p>4</p>');
document.write('                <p>5</p>');
document.write('              </div>');
document.write('            </div>');
document.write('        </div>');
document.write('        <div class="row mb-3">');
document.write('            <div class="col-md-6 col-lg-6">');
document.write('              <h3 class="text-center mb-4">Code</h3>');
document.write('                <div class="code_box_longest">');
document.write('                  <p>int <span class="random6">a</span> = <span class="text-warning">1</span>;</p>');
document.write('                  <p class="mt-2">for (; a <= 5;) &#123;</p>');
document.write('                  <p>&nbsp;&nbsp;&nbsp;&nbsp;printf(<span class="random5">&quot;<span class="random9">%d</span><span class="text-primary">\\n</span>&quot;</span>,<span class="random6">a</span>);</p>');
document.write('                  <p>&nbsp;&nbsp;&nbsp;&nbsp;a++;</p>');
document.write('                  <p>&#125;</p>');
document.write('                </div>');
document.write('            </div>');
document.write('            <div class="col-md-6 col-lg-6">');
document.write('              <h3 class="text-center mb-4">Output</h3>');
document.write('              <div class="code_box_long">');
document.write('                <p>1</p>');
document.write('                <p>2</p>');
document.write('                <p>3</p>');
document.write('                <p>4</p>');
document.write('                <p>5</p>');
document.write('              </div>');
document.write('            </div>');
document.write('        </div>');
document.write('        <div class="row mb-3">');
document.write('            <div class="col-md-6 col-lg-6">');
document.write('              <h3 class="text-center mb-4">Code</h3>');
document.write('                <div class="code_box_longest">');
document.write('                  <p>int <span class="random6">a</span> = <span class="text-warning">1</span>;</p>');
document.write('                  <p class="mt-2">for (; a <= 5; a++) &#123;</p>');
document.write('                  <p>&nbsp;&nbsp;&nbsp;&nbsp;printf(<span class="random5">&quot;<span class="random9">%d</span><span class="text-primary">\\n</span>&quot;</span>,<span class="random6">a</span>);</p>');
document.write('                  <p>&#125;</p>');
document.write('                </div>');
document.write('            </div>');
document.write('            <div class="col-md-6 col-lg-6">');
document.write('              <h3 class="text-center mb-4">Output</h3>');
document.write('              <div class="code_box_long">');
document.write('                <p>1</p>');
document.write('                <p>2</p>');
document.write('                <p>3</p>');
document.write('                <p>4</p>');
document.write('                <p>5</p>');
document.write('              </div>');
document.write('            </div>');
document.write('        </div>');
document.write('      </div>');
document.write('    </div>');
