document.write('    <div id="format_specifier" class="topic">');
document.write('      <div class="topic-name mb-4">');
document.write('        <h2>Format Specifier</h2>');
document.write('      </div>');
document.write('      <div class="topic-body">');
document.write('        <table class="table table-bordered table-striped table-dark">');
document.write('          <tr>');
document.write('            <th>Format Specifier</th>');
document.write('            <th>Usage</th>');
document.write('            <th>Description</th>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3">%d</td>');
document.write('            <td class="random3 bg-dark text-light">printf(<span class="random9">&quot;%d&quot;</span>, <span class="text-primary">5</span>);</td>');
document.write('            <td>Used to Print Integers</td>');
document.write('          </tr>');
document.write('          <tr class="bg-dark">');
document.write('            <td class="random3">%f</td>');
document.write('            <td class="random3">printf(<span class="random9">&quot;%f&quot;</span>, <span class="text-primary">7.45</span>);</td>');
document.write('            <td>Used to Print Decimals</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3">%c</td>');
document.write('            <td class="random3 bg-dark text-light">printf(<span class="random9">&quot;%c&quot;</span>, <span class="random5">&apos;H&apos;</span>);</td>');
document.write('            <td>Used to Print Character</td>');
document.write('          </tr>');
document.write('          <tr class="bg-dark">');
document.write('            <td class="random3">%s</td>');
document.write('            <td class="random3 bg-dark text-light">printf(<span class="random9">&quot;%s&quot;</span>, <span class="random5">&quot;Wood Cutter !&quot;</span>);</td>');
document.write('            <td>Used to Print String</td>');
document.write('          </tr>');
document.write('        </table>');
document.write('      </div>');
document.write('    </div>');
