document.write('    <div id="functions" class="topic">');
document.write('      <div class="topic-name mb-4">');
document.write('        <h2>Functions</h2>');
document.write('      </div>');
document.write('      <div class="topic-body">');
document.write('        <ul>');
document.write('          <li>');
document.write('            There are Two Types of functions:');
document.write('            <ol>');
document.write('              <li>');
document.write('                <span class="bold">Built-in / Pre-defined</span>');
document.write('                <ul>');
document.write('                  <li class="random3">main()</li>');
document.write('                  <li class="random3">printf()</li>');
document.write('                </ul>');
document.write('              </li>');
document.write('              <li class="bold">User Defined</li>');
document.write('            </ol>');
document.write('          </li>');
document.write('          <li>Execution of a C Program Starts From <span class="random3">main()</span></li>');
document.write('        </ul>');
document.write('        <div class="syntax_box">');
document.write('          <p class="mt-2">returnType function_name(parameters) &#123;</p>');
document.write('          <p>&nbsp;&nbsp;&nbsp;&nbsp;return parameter1+parameter2;</p>');
document.write('          <p>&#125;</p>');
document.write('        </div>');
document.write('        <div class="row">');
document.write('            <div class="col-md-6 col-lg-6">');
document.write('              <h2 class="text-center mb-4 mt-3">Code</h2>');
document.write('              <div class="code_box_longest">');
document.write('                <p class="bold"><span class="text-warning">#include</span> &lt;<span style="color: palegreen;">stdio.h</span>&gt;</p>');
document.write('                <p class="mb-4">int <span class="random7">loveYou</span><span class="text-primary">(</span>int <span class="random9">var1</span>, int <span class="random9">var2</span><span class="text-primary">)</span>;</p>');
document.write('                <p>int <span class="random7">main</span><span class="text-primary">()</span> &#123;</p>');
document.write('                <p>&nbsp;&nbsp;&nbsp;&nbsp;<span class="random7">loveYou</span><span class="text-primary">(</span><span class="text-warning">5</span>, <span class="text-warning">6</span><span class="text-primary">)</span>;</p>');
document.write('                  <p>&nbsp;&nbsp;&nbsp;&nbsp;<span class="text-info">return</span> <span class="text-warning">0</span>;</p>');
document.write('                <p class="mb-4">&#125;</p>');
document.write('                <p>int <span class="random7">loveYou</span><span class="text-primary">(</span>int <span class="random9">var1</span>, int <span class="random9">var2</span><span class="text-primary">)</span>&nbsp;&#123;</p>');
document.write('                  <p>&nbsp;&nbsp;&nbsp;&nbsp;printf(<span class="random5">&quot;</span><span class="random9">%d</span> <span class="random5">Loves</span> </span><span class="random9">%d</span>",<span class="random10">var1</span>,<span class="random10">var2</span>);</p>');
document.write('                <p>&#125;</p>');
document.write('              </div>');
document.write('            </div>');
document.write('            <div class="col-md-6 col-lg-6">');
document.write('              <h2 class="text-center mb-4 mt-3">Output</h2>');
document.write('              <div class="code_box_long">');
document.write('                <p>5 Loves 6</p>');
document.write('              </div>');
document.write('            </div>');
document.write('        </div>');
document.write('      </div>');
document.write('    </div>');
