document.write('    <div id="header_files" class="topic">');
document.write('      <div class="topic-name mb-4">');
document.write('        <h2>Header / Library Files:</h2>');
document.write('      </div>');
document.write('      <div class="topic-body mt-4">');
document.write('        <table class="table table-bordered table-dark">');
document.write('          <tr>');
document.write('            <td>');
document.write('              <span class="header_files_text">stdio.h</span><i class="fab fa-windows ml-4"></i><i class="fab fa-linux ml-4"></i>');
document.write('            </td>');
document.write('            <td>');
document.write('              <span class="header_files_text">conio.h</span><i class="fab fa-windows ml-4"></i>');
document.write('            </td>');
document.write('            <td>');
document.write('              <span class="header_files_text">curses.h</span><i class="fab fa-linux ml-4"></i>');
document.write('            </td>');
document.write('          </tr>');
document.write('        </table>');
document.write('        <div class="paragraph">');
document.write('          <div class="p1">');
document.write('            <p>Header Files Extension = .h</p>');
document.write('          </div>');
document.write('          <div class="p2">');
document.write('            <p>#include &lt;<span class="random1">stdio.h</span>&gt;</p>');
document.write('          </div>');
document.write('        </div>');
document.write('      </div>');
document.write('    </div>');
