document.write('    <div id="identifier" class="topic">');
document.write('      <div class="topic-name mb-4">');
document.write('        <h2>Identifier:</h2>');
document.write('      </div>');
document.write('      <div class="topic-body">');
document.write('        <ul>');
document.write('          <li>It is a Name given to a variable, constant, function etc</li>');
document.write('          <li>It should be of &lt;= 31 characters !</li>');
document.write('          <li>It starts with alphabet or underscore _</li>');
document.write('        </ul>');
document.write('      </div>');
document.write('    </div>');
