document.write('    <div id="if_else" class="topic">');
document.write('      <div class="topic-name mb-4">');
document.write('        <h2>if else</h2>');
document.write('      </div>');
document.write('      <div class="topic-body">');
document.write('        <p class="mb-5">If a Condition Evaluates to True, then its body block starts Execution !</p>');
document.write('        <div class="row">');
document.write('          <div class="col-sm-4">');
document.write('            <div class="code_box_longest">');
document.write('              <p>if (condition) &#123;</p>');
document.write('              <p>&nbsp;&nbsp;&nbsp;printf(<span class="random5">&quot;YAY !&quot;</span>);</p>');
document.write('              <p>&#125;</p>');
document.write('            </div>');
document.write('          </div>');
document.write('          <div class="col-sm-4">');
document.write('            <div class="code_box_longest">');
document.write('              <p>if (condition) &#123;</p>');
document.write('              <p>&nbsp;&nbsp;&nbsp;printf(<span class="random5">&quot;YAY !&quot;</span>);</p>');
document.write('              <p>&#125;</p>');
document.write('              <p>else &#123;</p>');
document.write('              <p>&nbsp;&nbsp;&nbsp;printf(<span class="random5">&quot;NAY !&quot;</span>);</p>');
document.write('              <p>&#125;</p>');
document.write('            </div>');
document.write('          </div>');
document.write('          <div class="col-sm-4">');
document.write('            <div class="code_box_longest">');
document.write('              <p>if (condition1) &#123;</p>');
document.write('              <p>&nbsp;&nbsp;&nbsp;printf(<span class="random5">&quot;YAY !&quot;</span>);</p>');
document.write('              <p>&#125;</p>');
document.write('              <p>else if (condition2) &#123;</p>');
document.write('              <p>&nbsp;&nbsp;&nbsp;printf(<span class="random5">&quot;WHOA !&quot;</span>);</p>');
document.write('              <p>&#125;</p>');
document.write('              <p>else if (condition3) &#123;</p>');
document.write('              <p>&nbsp;&nbsp;&nbsp;printf(<span class="random5">&quot;Amazing !&quot;</span>);</p>');
document.write('              <p>&#125;</p>');
document.write('              <p>else &#123;</p>');
document.write('              <p>&nbsp;&nbsp;&nbsp;printf(<span class="random5">&quot;NAY !&quot;</span>);</p>');
document.write('              <p>&#125;</p>');
document.write('            </div>');
document.write('          </div>');
document.write('        </div>');
document.write('        </div>');
document.write('    </div>');
