document.write('    <div id="increment_decrement" class="topic">');
document.write('      <div class="topic-name mb-4">');
document.write('        <h2>Increment / Decrement Operator</h2>');
document.write('      </div>');
document.write('      <div class="topic-body">');
document.write('        <table class="table table-bordered table-primary table-striped">');
document.write('          <tr>');
document.write('            <th>Name</th>');
document.write('            <th>Operator</th>');
document.write('            <th>Postfix Form</th>');
document.write('            <th>Prefix Form</th>');
document.write('            <th>Description</th>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td>Increment Operator</td>');
document.write('            <td class="random3">++</td>');
document.write('            <td class="random3">a++;</td>');
document.write('            <td class="random3">++a;</td>');
document.write('            <td>Adds 1 in variable a</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td>Decrement Operator</td>');
document.write('            <td class="random3">--</td>');
document.write('            <td class="random3">a--;</td>');
document.write('            <td class="random3">--a;</td>');
document.write('            <td>Subtracts 1 from variable a</td>');
document.write('          </tr>');
document.write('        </table>');
document.write('        <p class="nice_note">C++ is an increment on C</p>');
document.write('      </div>');
document.write('    </div>');
