document.write('    <div id="logical_operator" class="topic">');
document.write('      <div class="topic-name mb-4">');
document.write('        <h2>Logical Operators</h2>');
document.write('      </div>');
document.write('      <div class="topic-body">');
document.write('        <table class="table table-bordered table-hover table-warning">');
document.write('          <tr>');
document.write('              <th>Name</th>');
document.write('              <th>Operator</th>');
document.write('              <th>Usage</th>');
document.write('              <th>Description</th>');
document.write('          </tr>');
document.write('        <tr>');
document.write('          <td>NOT</td>');
document.write('          <td class="random3">!</td>');
document.write('          <td><span class="random3">!(5&lt;2)</span></td>');
document.write('          <td>Evaluates if Not 5 Less than 2</td>');
document.write('        </tr>');
document.write('        <tr>');
document.write('          <td>AND</td>');
document.write('          <td class="random3">&amp;&amp;</td>');
document.write('          <td><span class="random3">(5&gt;2) && (5&lt;10)</span></td>');
document.write('          <td>Evaluates if 5 is Greater than 2 and 5 is less than 10</td>');
document.write('        </tr>');
document.write('        <tr>');
document.write('          <td>OR</td>');
document.write('          <td class="random3">||</td>');
document.write('          <td><span class="random3">(6&gt;7) || (5&lt;10)</span></td>');
document.write('          <td>Evaluates if 6 is Greater than 7 or 5 is less than 10</td>');
document.write('        </tr>');
document.write('      </table>');
document.write('      </div>');
document.write('    </div>');
