document.write('    <div id="preprocessor_directives" class="topic">');
document.write('      <div class="topic-name mb-4">');
document.write('        <h2 class="">Preprocessor Directives:</h2>');
document.write('      </div>');
document.write('      <div class="topic-body mt-4">');
document.write('        <ul>');
document.write('          <li>');
document.write('            #include');
document.write('            <ul>');
document.write('              <li class="ml-5">#include &lt;stdio.h&gt;</li>');
document.write('            </ul>');
document.write('          </li>');
document.write('          <li>');
document.write('            #define');
document.write('            <ul>');
document.write('              <li class="ml-5">#define PI 3.1415</li>');
document.write('            </ul>');
document.write('          </li>');
document.write('          <li>');
document.write('            #undef');
document.write('            <ul>');
document.write('              <li class="ml-5">#undef PI</li>');
document.write('            </ul>');
document.write('          </li>');
document.write('          <li>');
document.write('            #pragma');
document.write('            <ul>');
document.write('              <li class="ml-5">#pragma startup function_name</li>');
document.write('              <li class="ml-5">#pragma exit function_name</li>');
document.write('            </ul>');
document.write('          </li>');
document.write('        </ul>');
document.write('      </div>');
document.write('    </div>');
