document.write('    <div id="relational_operator" class="topic">');
document.write('      <div class="topic-name mb-4">');
document.write('        <h2>Relational Operator</h2>');
document.write('      </div>');
document.write('      <div class="topic-body">');
document.write('        <table class="table table-bordered table-hover table-striped table-success">');
document.write('          <tr>');
document.write('            <th>Name</th>');
document.write('            <th>Operator</th>');
document.write('            <th>Usage</th>');
document.write('            <th>Description</th>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td>Not Equal</td>');
document.write('            <td class="random3">!=</td>');
document.write('            <td><span class="random3">(5 != 3)</span></td>');
document.write('            <td>Evaluates if 5 is not equal 3</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td>Less Than</td>');
document.write('            <td class="random3">&lt;</td>');
document.write('            <td><span class="random3">(5 < 3)</span></td>');
document.write('            <td>Evaluates if 5 is less than 3</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td>Greater Than</td>');
document.write('            <td class="random3">&gt;</td>');
document.write('            <td><span class="random3">(5 > 3)</span></td>');
document.write('            <td>Evaluates if 5 is Greater than 3</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td>Less Than or Equal to</td>');
document.write('            <td class="random3">&lt;=</td>');
document.write('            <td><span class="random3">(5 <= 5)</span></td>');
document.write('            <td>Evaluates if 5 is Less than or Equal to 5</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td>Greater Than or Equal to</td>');
document.write('            <td class="random3">&gt;=</td>');
document.write('            <td><span class="random3">(10 >= 7)</span></td>');
document.write('            <td>Evaluates if 10 is Greater than or Equal to 7</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td>Equal to</td>');
document.write('            <td class="random3">==</td>');
document.write('            <td><span class="random3">(20 == 10)</span></td>');
document.write('            <td>Evaluates if 20 is Equal to 10</td>');
document.write('          </tr>');
document.write('        </table>');
document.write('      </div>');
document.write('    </div>');
