document.write('    <div id="statement_terminator" class="topic">');
document.write('      <div class="topic-name mb-4">');
document.write('        <h2>Statement Terminator</h2>');
document.write('      </div>');
document.write('      <div class="topic-body">');
document.write('        <p>Semicolon <span class="random3">;</span> is called Statement Terminator.</p>');
document.write('        <p>It it Used To Terminate Statements !</p>');
document.write('        <p class="code_block">printf(<span class="random5">&quot;Don&apos;t Hate Programming !&quot;</span>);</p>');
document.write('      </div>');
document.write('    </div>');
