document.write('    <div id="strings" class="topic">');
document.write('      <div class="topic-name mb-4">');
document.write('        <h2>Strings</h2>');
document.write('      </div>');
document.write('      <div class="topic-body">');
document.write('        <p>String are similar to character</p>');
document.write('        <p>Any Text Enclosed in Double Quotes is called String !</p>');
document.write('        <table class="table table-bordered table-dark table1">');
document.write('          <tr>');
document.write('            <td><span class="random2">&quot;Jungle&quot;</span></td>');
document.write('            <td><span class="random2">&quot;Preety Lady&quot;</span></td>');
document.write('            <td><span class="random2">&quot;6ix 9ine&quot;</span></td>');
document.write('          </tr>');
document.write('        </table>');
document.write('        <p class="code_block">char <span class="text-warning">name[20]</span> = <span class="random2">&quot;Selena Gomez !&quot;</span>;</p>');
document.write('        <h2 class="mt-4">INBUILT FUNCTIONS FOR STRINGS</h2>');
document.write('        <table class="table table-bordered table-hover table-striped table-dark">');
document.write('          <tr>');
document.write('            <th>Functions</th>');
document.write('            <td><span class="bold">Description</span> <span class="text-warning ubuntu-font">(LIB: <span class="random6">strings.h</span>)</span></td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3 text-danger">strcat()</td>');
document.write('            <td>Concatenates str2 at the end of str1</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3 text-danger">strncat()</td>');
document.write('            <td>Appends a portion of string to another</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3 text-danger">strcpy()</td>');
document.write('            <td>Copies str2 into str1</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3 text-danger">strncpy()</td>');
document.write('            <td>Copies given number of characters of one string to another</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3 text-danger">strlen()</td>');
document.write('            <td>Gives the length of str1</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3 text-danger">strcmp()</td>');
document.write('            <td>Returns 0 if str1 is same as str2. Returns &lt;0 if str1 &lt; str2. Returns &gt;0 if str1 &gt; str2</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3 text-danger">strcmpi()</td>');
document.write('            <td>Same as strcmp() function. But, this function negotiates case. &quot;A&quot; and &quot;a&quot; are treated as same.</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3 text-danger">strchr()</td>');
document.write('            <td>Returns pointer to first occurrence of char in str1</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3 text-danger">strrchr()</td>');
document.write('            <td>last occurrence of given character in a string is found</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3 text-danger">strstr()</td>');
document.write('            <td>Returns pointer to first occurrence of str2 in str1</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3 text-danger">strrstr()</td>');
document.write('            <td>Returns pointer to last occurrence of str2 in str1</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3 text-danger">strdup()</td>');
document.write('            <td>Duplicates the string</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3 text-danger">strlwr()</td>');
document.write('            <td>Converts string to lowercase</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3 text-danger">strupr()</td>');
document.write('            <td>Converts string to uppercase</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3 text-danger">strrev()</td>');
document.write('            <td>Reverses the given string</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3 text-danger">strset()</td>');
document.write('            <td>Sets all character in a string to given character</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3 text-danger">strnset()</td>');
document.write('            <td>It sets the portion of characters in a string to given character</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td class="random3 text-danger">strtok()</td>');
document.write('            <td>Tokenizing given string using delimiter</td>');
document.write('          </tr>');
document.write('        </table>');
document.write('      </div>');
document.write('    </div>');
