document.write('    <div id="switch" class="topic">');
document.write('      <div class="topic-name mb-4">');
document.write('        <h2>Switch</h2>');
document.write('      </div>');
document.write('      <div class="topic-body">');
document.write('        <div class="code_box_longest">');
document.write('          <p>switch (n) &#123;</p>');
document.write('          <p>&nbsp;&nbsp;&nbsp;case 1:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="text-warning">//</span> <span class="text-secondary">code to be executed if n = 1;</span></p>');
document.write('          <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;printf(<span class="random5">&quot;YAY !&quot;</span>);</p>');
document.write('          <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;</p>');
document.write('          <p>&nbsp;&nbsp;&nbsp;case 2:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="text-warning">//</span> <span class="text-secondary">code to be executed if n = 2;</span></p>');
document.write('          <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;printf(<span class="random5">&quot;Habibi !&quot;</span>);</p>');
document.write('          <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;break;</p>');
document.write('          <p>&nbsp;&nbsp;&nbsp;default:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="text-warning">//</span> <span class="text-secondary">code to be executed if n doesn&apos;t match any cases</span></p>');
document.write('          <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;printf(<span class="random5">&quot;Cheap Thrills !&quot;</span>);</p>');
document.write('          <p>&#125;</p>');
document.write('        </div>');
document.write('      </div>');
document.write('    </div>');
