document.write('    <div id="type_casting" class="topic">');
document.write('      <div class="topic-name mb-4">');
document.write('        <h2>Type Casting</h2>');
document.write('      </div>');
document.write('      <div class="topic-body">');
document.write('        <p>Converting a DataType to another is Called Type Casting.</p>');
document.write('        <table class="table table-bordered table-hover table-striped table-danger">');
document.write('          <tr>');
document.write('            <th>Type</th>');
document.write('            <th>Description</th>');
document.write('          </tr>');
document.write('          <tr>');
document.write('          <td>Implicit Type Casting</td>');
document.write('          <td>Auto Performed By Compiler</td>');
document.write('          </tr>');
document.write('          <tr>');
document.write('            <td>Explicit Type Casting</td>');
document.write('            <td>Performed By Programmer !</td>');
document.write('          </tr>');
document.write('        </table>');
document.write('        <br>');
document.write('        <div class="row">');
document.write('          <div class="col-md-6 col-lg-6">');
document.write('            <div class="code_box_long">');
document.write('              <p><span class="text-warning">//</span> <span class="text-secondary">Implicit</span></p>');
document.write('              <p>printf(<span class="random5">&quot;%c&quot;</span>,<span class="text-warning">99</span>);</p>');
document.write('            </div>');
document.write('          </div>');
document.write('          <div class="col-md-6 col-lg-6">');
document.write('            <div class="code_box_long">');
document.write('              <p><span class="text-warning">//</span> <span class="text-secondary">Explicit</span></p>');
document.write('              <p>printf(<span class="random5">&quot;%c&quot;</span>,<span class="text-info">(char)</span><span class="text-warning">98</span>);</p>');
document.write('            </div>');
document.write('          </div>');
document.write('        </div>');
document.write('      </div>');
document.write('    </div>');
