document.write('    <div id="while_loop" class="topic">');
document.write('      <div class="topic-name mb-4">');
document.write('        <h2>while Loop</h2>');
document.write('      </div>');
document.write('      <div class="topic-body">');
document.write('        <p>Loop is a sequence of instructions that is continually repeated until a certain condition is reached !</p>');
document.write('        <h3 class="text-center">Syntax</h3>');
document.write('        <div class="syntax_box">');
document.write('          <p class="mt-3">while (condition) &#123;</p>');
document.write('            <p>&nbsp;&nbsp;&nbsp;&nbsp;printf(&quot;Confused ?&quot;);</p>');
document.write('          <p>&#125;</p>');
document.write('        </div>');
document.write('        <div class="row mt-5">');
document.write('          <div class="col-sm-6">');
document.write('            <h3 class="text-center mb-4">Code</h3>');
document.write('            <div class="code_box_long">');
document.write('              <p>int <span class="random6">a</span> = <span class="text-warning">1</span>;</p>');
document.write('              <p>while (<span class="random7">a &lt; 5</span>) &#123;</p>');
document.write('              <p>&nbsp;&nbsp;&nbsp;&nbsp;printf(<span class="random5">&quot;<span class="random9">%d</span><span class="text-primary">\n</span>&quot;</span>,<span class="random6">a</span>);</p>');
document.write('              <p>&nbsp;&nbsp;&nbsp;&nbsp;a++;</p>');
document.write('              <p>&#125;</p>');
document.write('            </div>');
document.write('          </div>');
document.write('          <div class="col-sm-6">');
document.write('            <h3 class="text-center mb-4">Output</h3>');
document.write('            <div class="code_box_long">');
document.write('              <p>1</p>');
document.write('              <p>2</p>');
document.write('              <p>3</p>');
document.write('              <p>4</p>');
document.write('            </div>');
document.write('          </div>');
document.write('        </div>');
document.write('      </div>');
document.write('    </div>');
